spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aggr
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true

poll-rate: 300000
